sudo: required
services:
- docker
language: scala
script:
- "./gradlew check -i"
- "./gradlew integrationtest -i"
- "./gradlew pushDockerImage -i"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: Zx6IHcMfJftRuM+jQszQCpIeckvC4qWZaNIbpN7vVd0NwF6StfJOwBxWt9qG2vf52krZL7r6IduToIQ4v3AJfYf2PpgygRh4/AgqMekCu5vxxoHkWGQ478Pmeq+1tCL0OwTcgoBAsm79ANdo3gS2oYzOuClaMGUtfknf3bTcZA6YSF9iuTzpUQBNKKmytQX5DD6PgDXYHTYin2T8tADT5VnmECh4sxyc7W7BKlcOtb2q6VsBTuZAm6xQTRsx+6UbGEr3I5In9ep3tFwhFZwyq6L3lfSNyEA21sumwh5vMDQvSZ5dM5iM/DtkOoEDYbspU1KKOg/XQxv/440CD/pHYwun+rTXApj4ulDGwC4CpOr84ezaJzbqdLK32DHO7eBoIpIZIoeDy+Q5Jx/vg9IXvM9MMe/UJ4ucpoBQicphyy6LU7xX2rrp7ZgFIBnWBr4Q81CW5dKDROWj41tnflWMHG0oFRcgUjxLQBpeDMxY0UxeJ3QRr0UK2ISaqiSHdJqXkfdBaxlSScxiyDOp1aFqlHPxxOr6J/V8RDRj4prgrhvufqUhMb5+f7oTXici0WsfE+aVE9xYPFWn+By3Ixuv1eQA8RY87nZwdMQ9qiq+1nUyAmC4/okdfH6/KBByc7Hso3fPHTDnMsfRowjzJwoDq6DvxRhfylQpKuWe5KoqxEY=
  - DOCKER_USER=thijslemmens