version: '3'

services:
  carbon-postgres:
    image: ${DOCKER_IMAGE}
    ports:
    - 2003
    environment:
#      - JAVA_OPTS=-Ddb.host=timescaledb -Ddb.port=5432
    - DB_HOST=timescaledb
    - DB_PORT=5432

  timescaledb:
    image: timescale/timescaledb
    ports:
    - 2345:5432
    environment:
    - POSTGRES_USER=timescale
    - POSTGRES_PASSWORD=timescale
    - POSTGRES_DB=timescale

  grafana:
    image: grafana/grafana
    ports:
    - 3000