version: '3'

services:
  carbon-postgres:
    image: ${DOCKER_IMAGE}
    ports:
      - :2003:2003
    environment:
      - JAVA_OPTS=-Ddb.host=timescaledb -Ddb.port=5432
#      Following does not work. Probably because of https://github.com/docker-library/openjdk/issues/135
#      - db.host=timescaledb
#      - db.port=5432

  timescaledb:
    image: timescale/timescaledb
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
    - :5432:5432
    environment:
      - POSTGRES_USER=timescale
      - POSTGRES_PASSWORD=timescale
      - POSTGRES_DB=timescale

  grafana:
    image: grafana/grafana
    ports:
    - :3000:3000